version: "3.6"
services:
  extrafeatures:
    container_name: extrafeatures
    image: index.docker.io/aleksioprime/extrafeatures
    command: python app.py
    environment:
      - URL=https://extrafeatures.aledev.ru/
      - HOST=0.0.0.0
      - PORT=5003
    volumes:
      - ./instance:/app/instance
    networks:
      - main
    ports:
      - "5003:5003"
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --scope extrafeatures
networks:
  main:
    driver: bridge